name: StaceyMoore
favicon: null
layout_spectrum: 0.36002860427834094
typography_spectrum: 0.2388887880370021
title: Balanced Living Guru
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03951812954619527
  lightness: 0.34097136789932847
  saturation: 0.47715095058083534
  rhythmicContrast: 0.9700897317379713
purpose: []
